#!/bin/bash
#PBS -P ERL					
#PBS -l select=1:ncpus=16:mem=16GB:ngpus=1
#PBS -l walltime=168:00:00
#PBS -q defaultQ
#PBS -j oe

cd /home/jgre3244/rl_exp/

# torch 1.9.0 complied with MAGMA 2.5.3 (also loads CUDA 10.2.89)
module load python/3.8.2
module load magma/2.5.3

# pip install (or upgrade) dependencies
pip install gym pybullet
pip install gym pybullet --upgrade

python main.py
# python scripts/exp_multiverse.py